### ISSUE TITLE
when setting up repeat-aft with new document models, get api.models.DoesNotExist: Document matching query does not exist

### ISSUE THREAD

**Issue by cmw48** [ripeta/repeat-aft#146]
using repeat-aft branch nc-test and repeat-plugins branch nc-dev with the authentication changes in the most recent pull, both Elly and I have local installations that are creating a {paper} but no {documents} created.  Auth token is working correctly.
```
ERROR 02-07-2019 05:08:55 PM Internal Server Error: /api/v0/extract/2
Traceback (most recent call last):
  File "/home/chris/.local/envs/ing1/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/chris/.local/envs/ing1/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chris/.local/envs/ing1/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chris/.local/envs/ing1/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/chris/.local/envs/ing1/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/chris/.local/envs/ing1/lib/python3.6/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/home/chris/.local/envs/ing1/lib/python3.6/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/chris/.local/envs/ing1/lib/python3.6/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/chris/pydev/repeat-aft/repeat/api/views.py", line 239, in get
    text, _ = paper.get_text()
  File "/home/chris/pydev/repeat-aft/repeat/api/models.py", line 210, in get_text
    doc = Document.objects.get(paper=self.id,file_type='pdf')
  File "/home/chris/.local/envs/ing1/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/chris/.local/envs/ing1/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
api.models.DoesNotExist: Document matching query does not exist.

```

**Comment by cmw48** [comment]
This error occurred because authentication was restricting the internal API access for ingest add and ingest-based extraction.  Once authentication errors were corrected and papers were added to a blank repeat-aft with datacopy, this error did not recur.  Closed.
