### ISSUE TITLE
API url to drill down to api_value values by paper

### ISSUE THREAD

**Issue by ejcramer** [ripeta/repeat-aft#91]
You can get all the values with this url:
http://localhost/api/v0/values

Currently, this url gives you the value for api_value.id (pk)
http://localhost/api/v0/values/2

For the front end, I would like the API url to also find values by api_paper.id (pk)

http://localhost:8000/api/v0/values/value/value_id/paper_id
http://localhost:8000/api/v0/values/2/1

Otherwise, I need to iterate thru all the values and pull out the ones with the paper id that I want to show.  With lots of papers, this is not tenable.

**Comment by ejcramer** [comment]
Need to research how to go about doing this. Needed for betatesting interface.  Performance issue.

**Comment by ejcramer** [comment]
I get this error when running the latest commit (0cbdc52) "Add query filters to values api..."
Reverted back to commit (cc6ea0b) "small changes to django...", and it works as expected.
Go back to latest and same error.

(env) ellens-mbp:repeat-aft ejc$ ./setup.py build
running build
running build_py
copying repeat/api/views.py -> build/lib/api
running egg_info
writing repeat/repeat_aft.egg-info/PKG-INFO
writing dependency_links to repeat/repeat_aft.egg-info/dependency_links.txt
writing top-level names to repeat/repeat_aft.egg-info/top_level.txt
reading manifest file 'repeat/repeat_aft.egg-info/SOURCES.txt'
writing manifest file 'repeat/repeat_aft.egg-info/SOURCES.txt'
running build_scripts
(env) ellens-mbp:repeat-aft ejc$ ./setup.py test
running test
running egg_info
writing repeat/repeat_aft.egg-info/PKG-INFO
writing dependency_links to repeat/repeat_aft.egg-info/dependency_links.txt
writing top-level names to repeat/repeat_aft.egg-info/top_level.txt
reading manifest file 'repeat/repeat_aft.egg-info/SOURCES.txt'
writing manifest file 'repeat/repeat_aft.egg-info/SOURCES.txt'
running build_ext
Base Dir: /Users/ejc/ricochet/repeat-aft/repeat/repeat_ml
imported with repeat_ml prefixed
django.setup() not required for model imports
Media root: /tmp/repeat-media
GloVe_dir = /Users/ejc/ricochet/repeat-aft/repeat/repeat_ml/GloVe
token_dir = /tmp/repeat-media/tokenizer/
model_dir = /tmp/repeat-media/nn_model/
Attempting to open file: /tmp/repeat-media/tokenizer/testtokenizer.pickle
Failed to load tokenizer
Variable found.
Failed to save tokenizer to api_variable
Creating test database for alias 'default'...
Traceback (most recent call last):
  File "./setup.py", line 14, in <module>
    test_suite="tests.runtests")
  File "/Users/ejc/ricochet/repeat-aft/env/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/ejc/ricochet/repeat-aft/env/lib/python3.6/site-packages/setuptools/command/test.py", line 226, in run
    self.run_tests()
  File "/Users/ejc/ricochet/repeat-aft/env/lib/python3.6/site-packages/setuptools/command/test.py", line 248, in run_tests
    exit=False,
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/main.py", line 141, in parseArgs
    self.createTests()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/main.py", line 148, in createTests
    self.module)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 219, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 219, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 204, in loadTestsFromName
    test = obj()
  File "/Users/ejc/ricochet/repeat-aft/repeat/tests.py", line 23, in runtests
    failures = test_runner.run_tests([HERE])
  File "/Users/ejc/ricochet/repeat-aft/env/lib/python3.6/site-packages/django/test/runner.py", line 602, in run_tests
    self.run_checks()
  File "/Users/ejc/ricochet/repeat-aft/env/lib/python3.6/site-packages/django/test/runner.py", line 562, in run_checks
    call_command('check', verbosity=self.verbosity)
  File "/Users/ejc/ricochet/repeat-aft/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/Users/ejc/ricochet/repeat-aft/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/ejc/ricochet/repeat-aft/env/lib/python3.6/site-packages/django/core/management/commands/check.py", line 68, in handle
    fail_level=getattr(checks, options['fail_level']),
  File "/Users/ejc/ricochet/repeat-aft/env/lib/python3.6/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/ejc/ricochet/repeat-aft/env/lib/python3.6/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/ejc/ricochet/repeat-aft/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/ejc/ricochet/repeat-aft/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/Users/ejc/ricochet/repeat-aft/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/Users/ejc/ricochet/repeat-aft/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/Users/ejc/ricochet/repeat-aft/env/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/ejc/ricochet/repeat-aft/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/ejc/ricochet/repeat-aft/env/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/ejc/ricochet/repeat-aft/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/ejc/ricochet/repeat-aft/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/ejc/ricochet/repeat-aft/repeat/repeat/urls.py", line 11, in <module>
    url(r'^api/v0/', include("api.urls")),
  File "/Users/ejc/ricochet/repeat-aft/env/lib/python3.6/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/ejc/ricochet/repeat-aft/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/ejc/ricochet/repeat-aft/repeat/api/urls.py", line 9, in <module>
    from api import views
  File "/Users/ejc/ricochet/repeat-aft/env/lib/python3.6/site-packages/pluginbase.py", line 410, in plugin_import
    fromlist, level)
  File "/Users/ejc/ricochet/repeat-aft/repeat/api/views.py", line 76, in <module>
    class ValueCRUD(generics.RetrieveUpdateDestroyAPIView):
  File "/Users/ejc/ricochet/repeat-aft/repeat/api/views.py", line 78, in ValueCRUD
    serializer_class = serializers.FooSerializer
AttributeError: module 'api.serializers' has no attribute 'FooSerializer'
