### ISSUE TITLE
Pull request Travis CI still failing

### ISSUE THREAD

**Issue by ejcramer** [ripeta/repeat-aft#94]
Here's the Travis CI log:

======================================================================

FAIL: test_paper (api.tests.test_models.PaperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/ripeta/repeat-aft/repeat/api/tests/test_models.py", line 37, in test_paper
    set(json.loads(str(paper)).keys()))
AssertionError: Items in the second set but not the first:
'id'
'createdDate'
======================================================================

FAIL: test_extract (api.tests.test_views.ViewTests)
Test that variables are extracted properly
----------------------------------------------------------------------

Traceback (most recent call last):
  File "/home/travis/build/ripeta/repeat-aft/repeat/api/tests/test_views.py", line 39, in test_extract
    c.get(paper_url).content)
AssertionError: b'{"funding":null,"grant_id":null}' != b'{"article_doi":null,"funding":null,"grant_id":null}'

======================================================================

FAIL: extract (api.analysis.analysis)
Doctest: api.analysis.analysis.extract

----------------------------------------------------------------------

Traceback (most recent call last):
  File "/opt/python/3.6.3/lib/python3.6/doctest.py", line 2199, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for api.analysis.analysis.extract
  File "/home/travis/build/ripeta/repeat-aft/repeat/api/analysis/analysis.py", line 19, in extract

----------------------------------------------------------------------

File "/home/travis/build/ripeta/repeat-aft/repeat/api/analysis/analysis.py", line 44, in api.analysis.analysis.extract

Failed example:
    extract("This research was funded by Wayne Enterprises.", "funding")

Expected:
    ('Wayne Enterprises', 'This research was funded by Wayne Enterprises.')

Got:
    ('This research was funded by Wayne Enterprises.', 'Wayne Enterprises', 'extracted', 'nltk search v1')

----------------------------------------------------------------------

Ran 16 tests in 0.265s

FAILED (failures=3)

**Comment by ejcramer** [comment]
Looks good!  I'll merge this into the master branch.
