### ISSUE TITLE
Unit test errors (there's more)

### ISSUE THREAD

**Issue by ejcramer** [ripeta/repeat-aft#98]
The first one "TypeError: must be str, not list" sounded simple, but for some reason I'm not getting it.  The second one in test_views.py I could fix.

```
System check identified no issues (0 silenced).
E.......F.......
======================================================================
ERROR: test_actual_plugin (api.analysis.tests.test_analysis.PluginTests)
Call the "funding" plugin
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ejc/ricochet/repeat-aft/repeat/api/analysis/tests/test_analysis.py", line 34, in test_actual_plugin
    (sentence, result), self.extract(sentence, None, "funding")[:2])
  File "/Users/ejc/ricochet/repeat-aft/repeat/api/analysis/analysis.py", line 48, in extract
    plugin_paths = lmap(os.path.abspath, plugin_paths + [BASE_PLUGIN_DIR])
TypeError: must be str, not list

======================================================================
FAIL: test_extract (api.tests.test_views.ViewTests)
Test that variables are extracted properly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ejc/ricochet/repeat-aft/repeat/api/tests/test_views.py", line 35, in test_extract
    self.assertEqual(b'{"value":null}', c.get(var_url).content)
AssertionError: b'{"value":null}' != b'{"value":["No","Not Found"]}'

----------------------------------------------------------------------
Ran 16 tests in 0.367s

```

**Comment by ejcramer** [comment]
Just checked out Nick's latest code and there's now a new error:

```
System check identified no issues (0 silenced).
..E.............
======================================================================
ERROR: test_modulenotfound (api.analysis.tests.test_analysis.PluginTests)
When a module isn't found, an exception should be raised
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ejc/ricochet/repeat-aft/repeat/api/analysis/tests/test_analysis.py", line 22, in test_modulenotfound
    self.assertRaises(ImportError, self.extract, "", "fake_name")
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 728, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 177, in handle
    callable_obj(*args, **kwargs)
TypeError: extract() missing 1 required positional argument: 'variable_name'

----------------------------------------------------------------------
Ran 16 tests in 0.485s

FAILED (errors=1)
Destroying test database for alias 'default'...
```

**Comment by DragonWriter** [comment]
Yeah, that commit should resolve it. Was about to do the same before realizing you made this commit.
